codecov:
  notify:
    require_ci_to_pass: true

comment:
  behavior: default
  layout: header, diff, tree
  require_changes: false

coverage:
  precision: 2
  range: "40..80"
  round: nearest
  status:
    changes: false
    patch: true
    project: true
  ignore:
  - _.*
  - tests/.*

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false

                  
